version: '3.8'

services:

  frontend:
    labels:
      shipyard.route: '/'
    build: 'frontend'
    environment:
      CI: 'true'
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
    ports:
      - '3000:3000'

  postgres:
    image: 'postgres:13.0-alpine'
    environment:
      POSTGRES_PASSWORD: 'obscure-password'
      POSTGRES_USER: 'obscure-user'
      POSTGRES_DB: 'app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  backend:
    labels:
      shipyard.before: 'npx sequelize-cli db:migrate'
      shipyard.route: '/api'
    build:
      context: ./backend/
    environment:
      DB_USER: 'obscure-user'
      DB_PASSWORD: 'obscure-password'
      DB_NAME: 'app'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    volumes:
      - './backend/src:/app/src'

  localstack:
    image: 'localstack/localstack'
    ports:
      - '4566:4566'
      - '4571:4571'

volumes:
  postgres: